[project]
name = "iris"
version = "0.1.0"
description = "Iris SDK"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["asyncio>=3.4.3", "httpx>=0.28.1", "fastmcp>=2.10.6"]

[dependency-groups]
dev = ["dotenv>=0.9.9"]
